name: MLOps customer churn

on: 
  push: 
    branches: [dev,stage, main] 
  pull_request:
    branches: [dev,stage, main] 
  workflow_dispatch:  

permissions: 
  contents: write
  pull-requests: write

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install python libraries and uv      
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create virtual environment
        run: uv venv
      - name: Install requirements
        run: uv pip install -r requirements.txt
      
      - name: Install DVC with Azure support
        run: pip install "dvc[azure]"

      - name: Configure Azure credentials
        run: |
          dvc remote modify azure_remote account_name ${{ secrets.ACCOUNT_NAME }}
          dvc remote modify azure_remote account_key ${{ secrets.ACCOUNT_KEY }}

      - name: Pull data and models from DVC
        run: dvc pull

      - name: Train model
        run: uv run python src/train_model.py

      - name: Run unittests
        run: uv run python -m pytest tests/test_unittests.py
                  
      - name: Create classification reports
        run: | 
          echo "## Confusion matrix" > MLreport.md
          cat confusionmatrix.png >> MLreport.md
          echo "### Classification report" >> MLreport.md
          cat classification_report.txt >> MLreport.md
          echo "### Training History plot" >> MLreport.md 
          cat History.png >> MLreport.md
  stage:
    if: github.ref_name =='stage'    
    needs: dev
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4      

      - name: docker login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/cust-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/cust-app:latest   

     


      
